"""Zodiac sign

Revision ID: 0e121bdefae9
Revises: 3f883f37e457
Create Date: 2023-10-24 19:43:54.158490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e121bdefae9'
down_revision: Union[str, None] = '3f883f37e457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('zodiac_sign', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'zodiac_sign')
    # ### end Alembic commands ###
