"""oracle date

Revision ID: 8ffc8281a63a
Revises: b25677a0e70f
Create Date: 2023-11-02 22:43:00.614473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ffc8281a63a'
down_revision: Union[str, None] = 'b25677a0e70f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oracle_date_save', sa.Date(), nullable=False))
    op.drop_column('users', 'oracle')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oracle', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'oracle_date_save')
    # ### end Alembic commands ###
