"""oracle

Revision ID: b25677a0e70f
Revises: 0e121bdefae9
Create Date: 2023-11-02 21:33:26.614576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25677a0e70f'
down_revision: Union[str, None] = '0e121bdefae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oracle', sa.Integer(), nullable=False))
    op.drop_column('users', 'zodiac_sign')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('zodiac_sign', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('users', 'oracle')
    # ### end Alembic commands ###
